name: Get Kernel Update

on: 
  watch:
    types: [started]
  push:
    branches: 
      - master

env:
  KERNEL_VERSION: 4.14
  CAF_TAG: LA.UM.8.2.1.r1-05000-sdm660.0
  Upload_Link: https://github.com/tanz3/caf-4.14.git

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Downloading CAF Update
      run: |
        git clone https://source.codeaurora.org/quic/la/kernel/msm-$KERNEL_VERSION -b $CAF_TAG
        
    - name: Uploading CAF Update
      run: |
        git push --mirror $Upload_Link 
