name: Install bt

on: 
  release:
    types: [published]
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Get ip information
      run: sudo curl myip.ipip.net
   
    - name: Check Disk 
      run: sudo df -lh
 
    - name: Get Cpus information
      run: sudo cat /proc/cpuinfo
    
    - name: Check Internet Status
      run: sudo ip addr
      
    - name: Mtr information
      run: |
        sudo apt install mtr
        sudo mtr www.google.com
